complete -c os -f
complete -c os -l new  -d "create a new container"
complete -c os -l remove  -d "Remove a container"
complete -c os -l upgrade  -d "Upgrade all containers"
complete -c os -l use  -d "Enter inside the container"
complete -c os -l clean -d "Delete all containers"
complete -c os -l list  -d "List all containers"
complete -c os -l stop  -d "Stop all containers"
complete -c os -l pause  -d "Stop a container"
complete -c os -l run  -d "Run a command in the container"