#!/bin/bash

UPDATES=$(paru -Qu)

if [ -n "${UPDATES}" ]
then
	response=$(dunstify -i arch -a arch -A "up,ACCEPT" -A no,DECLINE "Run all updates")
	case $response in
	2)
	 	echo "do nothing"
	 	exit 0
 	;;
	"up")
		$(response) || exit 1
		exit 0
	;;
	*)
	 	echo "do nothing"
	 	exit 0
 	;;
 	esac
else
	dunstify -i arch -a arch "System is up do date"
	exit 0
fi
