pub const DIY: [&str; 13] = [
    "blender",
    "prusa-slicer",
    "superslicer",
    "bambustudio",
    "orca-slicer",
    "mattercontrol",
    "ideamaker",
    "slic3r",
    "icesl",
    "flashprint",
    "octoprint",
    "printrun",
    "repetier-host",
];
