pub const ASSEMBLY: [&str; 4] = ["binutils", "nasm", "fasm", "yasm"];
pub const GO: [&str; 10] = [
    "go",
    "go-tools",
    "gopls",
    "delve",
    "goreleaser",
    "gox",
    "ko",
    "revive",
    "staticcheck",
    "yaegi",
];
pub const R: [&str; 2] = ["r", "gcc-fortran"];
pub const PHP: [&str; 26] = [
    "php",
    "php-apache",
    "php-apcu",
    "php-cgi",
    "php-dblib",
    "php-embed",
    "php-enchant",
    "php-gd",
    "php-geoip",
    "php-grpc",
    "php-igbinary",
    "php-imagick",
    "php-memcache",
    "php-memcached",
    "php-mongodb",
    "php-pgsql",
    "php-phpdbg",
    "php-pspell",
    "php-redis",
    "php-snmp",
    "php-snuffleupagus",
    "php-sodium",
    "php-sqlite",
    "php-tidy",
    "php-xsl",
    "composer",
];

pub const PYTHON: [&str; 8] = [
    "python",
    "tk",
    "ipython",
    "bpython",
    "python-pip",
    "python-pipx",
    "python-poetry",
    "python-jedi",
];

pub const D: [&str; 5] = ["dmd", "dlang-dmd", "dtools", "dub", "ibphobos"];

pub const RUST: [&str; 43] = [
    "cargo",
    "rustup",
    "wargo-watch",
    "cargo-audit",
    "cargo-expand",
    "cargo-auditable",
    "cargo-about",
    "cargo-asm",
    "cargo-binstall",
    "cargo-bloat",
    "cargo-bundle-licenses",
    "cargo-c",
    "cargo-clone",
    "cargo-crev",
    "cargo-cyclonedx",
    "cargo-deb",
    "cargo-deny",
    "cargo-depgraph",
    "cargo-dist",
    "cargo-expand",
    "cargo-edit",
    "cargo-feature",
    "cargo-flamegraph",
    "cargo-fuzz",
    "cargo-generate",
    "cargo-license",
    "cargo-machete",
    "cargo-make",
    "cargo-modules",
    "cargo-msrv",
    "cargo-ndk",
    "cargo-outdated",
    "cargo-tauri",
    "cargo-tarpaulin",
    "cargo-spellcheck",
    "cargo-supply-chain",
    "cargo-shuttle",
    "cargo-nextest",
    "cargo-sort",
    "cargo-sweep",
    "cargo-wizard",
    "cargo-update",
    "cargo-zigbuild",
];

pub const C: [&str; 8] = [
    "gcc", "cmake", "valgrind", "distcc", "clang", "tcc", "musl", "glib2",
];
