complete -c os -f
complete -c os -l new  -d "Create a new box"
complete -c os -l remove  -d "Remove a box"
complete -c os -l upgrade  -d "Upgrade all boxes"
complete -c os -l use  -d "Enter inside a box"
complete -c os -l clean -d "Delete all boxes"
complete -c os -l list  -d "List all boxes"
complete -c os -l stop  -d "Stop all box"
complete -c os -l pause  -d "Stop a box"
complete -c os -l run  -d "Run the command in a box"
complete -c os -l help  -d "Display help message"